### ISSUE TITLE
Email subject no more contain advisory ID

### ISSUE THREAD

**Issue by andrewlukoshko** [AlmaLinux/errata-email-notifications#6]
Here is how it looks now:
`[Security Advisory] Important: rsync security update`

Here is how it was previously:
`[Security Advisory] ALSA-2022:5813: vim security update (Moderate)`

AFAIK there was some updates in errata JSON file so we need to adjust the script.

**Comment by javihernandez** [comment]
Sorry, this is a consequence of the last updates made to the errata data
generator in https://github.com/AlmaLinux/albs-web-server/pull/278 and I missed that one :disappointed: 

I already created https://github.com/AlmaLinux/errata-email-notifications/pull/7 to fix the problem ;)
